### ISSUE TITLE
Color issues

### ISSUE THREAD

**Issue by saphsara** [asiekierka/UnlimitedChiselWorks-Botany#1]
Hi, i decided to go with minecraft 1.12.2 and when i put this mod in the Binnie's Mods blocks are colorless they are all white.

no resource packs. 

Latest server log .. https://pastebin.com/jgbhRUHP

 i made a recording of it if you want me to send it to you.
 Thank you for looking into this
MODLIST:
    Better With Mods (by BeetoGuy)
    Better With Addons (by BordListian)
    Forestry (by SirSengir)
    Binnie's Mods (by Binnie567)
    Unlimited Chisel Works (by asiekierka)
    Unlimited Chisel Works - Botany (by asiekierka)
    WanionLib (by WanionCane)
    UniDict (by WanionCane)
    Mantle (by mDiyo)
    Tinkers Construct (by mDiyo)
    Pam's HarvestCraft (by MatrexsVigil)
    Baubles (by azanor)
    Botania (by Vazkii)
    Better Builder's Wands (by Portablejim)
    Redstone Flux (by TeamCoFH)
    CoFH Core (by TeamCoFH)
    CoFH World (by TeamCoFH)
    Thermal Foundation (by TeamCoFH)
    CodeChicken Lib 1.8.+ (by covers1624)
    Brandon's Core (by brandon3055)
    Draconic Evolution (by brandon3055)
    Industrial Craft (by Player)
    Tinkers' Tool Leveling (by bonusboni)
    Chest Transporter (by CubeX2)
    Cucumber (by BlakeBr0)
    Mystical Agriculture (by BlakeBr0)
    Astral Sorcery (by HellFirePvP)
    Ore Excavation (by Funwayguy)
    Mekanism (by aidancbrady)
    Mekanism Tools (by aidancbrady)
    Ceramics (by KnightMiner)
    Thermal Cultivation (by TeamCoFH)
    OMLib (by Keridos)
    OpenModularTurrets (by Poenjabiesous)
    ProjectE (by sinkillerj)
    Tinkers' Addons (by oitsjustjose)
    Inventory Pets (by Purplicious_Cow)
    Silent Lib (by SilentChaos512)
    Silent's Gems (by SilentChaos512)
    MMD OreSpawn (by jriwanek)
    Base Metals (by jriwanek)
    Silent's Gems: Extra Parts (by SilentChaos512)
    ConnectedTexturesMod (by tterrag1098)
    Chisel (by tterrag1098)
    BdLib (by bdew)
    Advanced Generators (by bdew)
    Chameleon (by jaquadro)
    Storage Drawers (by jaquadro)
    Immersive Engineering (by BluSunrize)
    Chisels & Bits (by AlgorithmX2)
    OpenBlocks Elevator (by VsnGamer)
    DecoCraft2 (by RazzleberryFox)
    AutoRegLib (by Vazkii)
    Quark (by Vazkii)
    Sonar Core (by Ollie_Lansdell)
    Hwyla (by TehNut)
    Storage Drawers Extras (by jaquadro)
    MalisisCore (by Ordinastie)
    MalisisDoors (by Ordinastie)
    Xtones (by TehNut)
    MrCrayfish's Furniture Mod (by Mr_Crayfish)
    CreativeCore (by CreativeMD)
    ItemPhysic Full (by CreativeMD)
    Psi (by Vazkii)
    Magical Psi (by wiiv)
    Corail Pillar (by Corail31)
    Rainbow Oak Trees (by csb987)
    Corail Pillar - Extension Chisel (by Corail31)
    Tomb Many Graves 2 (by M4thG33k)
    Corail Pillar - Extension Quark & Botania (by Corail31)
    Corail Pillar - Extension Forestry (by Corail31)
    ColorfulWater (by BillyGalbreath)
    Thermal Dynamics (by TeamCoFH)
    ValkyrieLib (by ValkyrieofNight)
    Environmental Tech (by ValkyrieofNight)
    Refined Storage (by raoulvdberge)
    Cyclops Core (by kroeser)
    Common Capabilities (by kroeser)
    Integrated Dynamics (by kroeser)
    Integrated Tunnels (by kroeser)
    Refined Storage Addons (by raoulvdberge)
    Immersive Tech (by ferroo2000)
    WirelessCharger (by ZLainSama)
    Fast Leaf Decay (by Olafskii)
    Farming for Blockheads (by BlayTheNinth)
    Bibliotheca (by EwyBoy)
    Cultivated Tech (by EwyBoy)
    Cooking for Blockheads (by BlayTheNinth)
    Actually Additions (by Ellpeck)
    Thermal Expansion (by TeamCoFH)
    Industrial Wires (by malte0811)
    Mekanism Generators (by aidancbrady)
    ET Lunar [Environmental Tech Addon] (by ValkyrieofNight)
    Magic Bees (by MysteriousAges)
    More Bees (by Tencao)
    Just Enough Items (JEI) (by mezz)
    JEI Bees (by bdew)
    Not Enough Items 1.8.+ (by covers1624)
    Natura (by mDiyo)
    Rockhounding Mod: Core (by GlobbyPotato)
    Rockhounding Mod: Rocks (by GlobbyPotato)
    Rockhounding Mod: Ore Tiers (by GlobbyPotato)
    Rockhounding Mod: Surface (by GlobbyPotato)
    JourneyMap (by techbrew)
    Inventory Tweaks (by Kobata)
    Mouse Tweaks (by YaLTeR97)
    NotEnoughIDs (by fewizz)
    JEI Integration (by SnowShock35)
    Just Enough HarvestCraft (JEHC) (by mrAppleXZ)
    Earthworks (by Alsnder)
    Flux Networks (by Ollie_Lansdell)
    Futurepack (by MCenderdragon)
    How 'Bout That Furniture (by Zundrel)
    Immersive Petroleum (by theFlaxbeard)
    Immersive Cables (by SanAndreasP)
    Iron Chests (by progwml6)
    Morpheus (by Quetzi)
    Roguelike Dungeons (by Greymerk)
    Redstone Paste (by FyberOptic)
    Waila Harvestability (by squeek502)
    Concrete Extends (by acnessdev)
    Random Things (by lumien231)
    Statues (by svennieke)
    FTBLib (by FTB)
    FTB Utilities (by FTB)
    FTB Guide Book (by EmoKiba)
    Flat Plains (by polyfiller)
    Futurepack Colorization Addon (by FuturepackAddonTeam)
    Environmental Materials (by ValkyrieofNight)

**Comment by Blatts12** [comment]
https://i.imgur.com/A9YHkHt.png
